title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rekales.github.io/dotnet-reviewer/

aux_links:
  Template Repository: https://github.com/rekales/dotnet-reviewer

nav_order: true